# Model Configuration
model:
  type: "codestral-latest"
  system_prompt: "You are a ROS2 expert. You will generate ROS2 elements based on user requirements. You will use the ROS2 API and follow the ROS2 conventions. You will use the ROS2 Python API for the generated code."
  parameters:
    temperature: 0.2

# Generation Settings
generation:
  max_attempts: 10
  evaluation_iterations: 30

# Metrics Collection
metrics:
  metrics_file: "generation_metrics.jsonl"
