# Model Configuration
model:
  type: "codestral-latest"
  api_key: "YOUR_API_KEY_HERE"
  system_prompt: |
    You are a ROS2 expert who specializes in service implementations.
    Generate clean, efficient python code that follows ROS2 best practices.
    Focus on proper error handling and input validation.
  parameters:
    temperature: 0.2

# Generation Settings
generation:
  max_attempts: 10
  evaluation_iterations: 1

# Test Settings
test:
  #! for ROS2 humble
  ws_setup: "source /opt/ros/humble/setup.bash && colcon build --packages-select object_height && source install/setup.bash"
  node_command: "ros2 run object_height object_height_service"
  test_command: "pytest -q -s -x src/object_height/test/test_service_node.py"

# Metrics Collection
metrics:
  metrics_file: "object_height_metrics.jsonl"

# Path to the generated code
output:
  output_file: "src/object_height/object_height/service_node.py"

# Input files used for prompting
input:
  interface_file: "src/object_height/srv/ObjectHeight.srv"
  test_file: "src/object_height/test/test_service_node.py"
